# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

# http://click.palletsprojects.com/en/5.x/python3/#python-3-surrogate-handling
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

Lint_task:
  container:
    image: python:3.8-slim
  install_script:
    - pip3 install -U bork .[testing]
  script:
    - flake8 --version
    - pylint --version
    - bork run lint

Linux_task:
  allow_failures: $CIRRUS_TASK_NAME =~ '.*-rc-.*'
  container:
    matrix:
      - image: python:3.6-slim
      - image: python:3.7-slim
      - image: python:3.8-slim
  install_script:
    - pip3 install -U bork .[testing]
  script:
    - python3 --version
    - bork run test
